version: "3.6"

services:
  web:
    # build: ./web
    image: localhost/mp-app-ek/web:0.0.1'
    environment:
      AUTH_SERVICE: auth:20080
    ports:
      - '8080:8080'
  auth:
    # build: ./auth
    image: localhost/mp-app-ek/auth:0.0.1
    expose:
      - '20080'
