version: "3.6"

services:
  web:
    image: mp-app-ek/web:0.0.1
    environment:
      AUTH_SERVICE: 'auth:20080'
    ports:
      - '8080:8080'
  auth:
    image: mp-app-ek/auth:0.0.1
    environment:
      PORT: ':20080'
    expose:
      - '20080'
